### ISSUE TITLE
In VR addon should be enable by default

### ISSUE THREAD

**Issue by DFOXpro** [RedK0d/CLICKABLE-FC3#20]
Expected behaviour:
Launch simulation and planes should be clickables

Current behaviour:
 After the simulation start plane is not clickable, the user must type LAlt+C to enable interactions

**Comment by RedK0d** [comment]
function post_initialize()
    dispatch_action(nil,Keys.iCommandCockpitClickModeOnOff) 

	local birth = LockOn_Options.init_conditions.birth_place

    if birth=="GROUND_HOT" or birth=="AIR_HOT" then
        
    elseif birth=="GROUND_COLD" then
    end
  

	

end

**Comment by RedK0d** [comment]
iCommandCockpitClickModeOnOff       =   363;

**Comment by DFOXpro** [comment]
just to add more to the discussion, the other clickable modules all start in a clickable state, then LAlt+C toggles to move camera.

Can I propose with this module start in clickeable state both in vr and flatscreen? then with LAlt+C toggles to move camera.

**Comment by RedK0d** [comment]
Yes, it is a very good proposal. I'll try to implement that via the options. Otherwise the module starts in clickable mode. Thank you for the feedback
