### ISSUE TITLE
scroll down knobs fails

### ISSUE THREAD

**Issue by DFOXpro** [RedK0d/CLICKABLE-FC3#23]
scroll down or (vr)hand-joystick to the left, over scroll icon knobs

Expected behaviour:
Trigger knob-down activity

Current behaviour:
Does nothing

This is reproducible with RWR volume and HUD bright knobs

**Comment by RedK0d** [comment]
I don't have VR to be able to verify and reproduce. However in non-VR mode both work, left to reduce, right to increase. Can anyone confirm or deny the bug in VR?

**Comment by DFOXpro** [comment]
To reproduce with the mouse is easy: instead of moving the move just roll the scroll wheel, scrollUp for increase or scrollDown for decrease, note if you previously set down the value(like hud brightness the easy to test) it's easy to set high value again with scroll, but it's not possible the way down.

I believe for VR it's registering the scroll action for the knuckle stick, I did the test with the reverbG2 controllers
