### ISSUE TITLE
"Toggle Mirrors" action still appears when cockpit is open

### ISSUE THREAD

**Issue by deadlyfishes** [RedK0d/CLICKABLE-FC3#24]
"Toggle Mirrors" action still appears when cockpit is open:
![image](https://user-images.githubusercontent.com/25260306/152203009-df9e14bc-27f4-402e-8641-a7648203a5d1.png)

Expected Result:
"Toggle Mirrors" action should only appear when cockpit is closed.

**Comment by RedK0d** [comment]
I can't manage to animate the connectors following the opening of the canopy. I followed the same process as for the animation of the meshes, I can see the connectors moving in ModelViewer, but not in DCS.
If anyone has a solution to this problem, I'm all ears.
In the meantime, I removed the two left and right connectors, and lowered the position just above the hud a little.
