### ISSUE TITLE
Yak-52 Cockpit clash

### ISSUE THREAD

**Issue by Swartbyron** [RedK0d/CLICKABLE-FC3#26]
SU-25T Cockpit apearing in the Yak-52

**Comment by RedK0d** [comment]
Please attach the yak's "entry.lua" file

**Comment by Swartbyron** [comment]
entry.lua for the Yak-52

[entry.zip](https://github.com/RedK0d/CLICKABLE-FC3/files/8009824/entry.zip)

**Comment by RedK0d** [comment]
fixed entry.lua file excluding the Yak-52.
Put it in Saved Games\DCS\Mods\tech\CLICKABLE-FC3 and you won't have YAK25T anymore
[entry.zip](https://github.com/RedK0d/CLICKABLE-FC3/files/8009887/entry.zip)

**Comment by Swartbyron** [comment]
Thanks, it works. :)
