### ISSUE TITLE
Cockpit Error in Spitfire (CW and non CW)

### ISSUE THREAD

**Issue by deadlyfishes** [RedK0d/CLICKABLE-FC3#34]
![image](https://user-images.githubusercontent.com/25260306/153649544-0a043a22-44cd-4d5a-bafb-8e3188872f0b.png)

`local self_ID = "Spitfire LF Mk. IX by Eagle Dynamics"

declare_plugin(
    self_ID,
    {
        installed = true, -- if false that will be place holder, or advertising
        dirName = current_mod_path,

        fileMenuName = _("Spitfire LF Mk. IX"),
        displayName = _("Spitfire LF Mk. IX"),
        shortName = "Spitfire LF Mk. IX",
        update_id = "SPITFIRE-MKIX",
        registryPath     = "Eagle Dynamics\\SpitfireLFMkIX",
        version = __DCS_VERSION__,
        state = "installed",
        info = _("The British Spitfire is one of the most iconic fighter aircraft of World War II. Most famous for its role in the Battle of Britain, the Spitfire served as Britain's primary fighter during the entirety of the war. The Spitfire combines graceful lines, eye-watering dogfight performance, and heavy firepower in its later variants. For DCS World, we are happy to bring you the most accurate and realistic simulation of the Spitfire LF Mk IX ever created."),

        binaries = {
            'SpitfireLFMkIX'
        },

        InputProfiles = {
            ["SpitfireLFMkIX"] = current_mod_path .. '/Input/SpitfireLFMkIX',
            ["SpitfireLFMkIX_easy"] = current_mod_path .. '/Input/SpitfireLFMkIX_easy',  
            ["SpitfireLFMkIXCW"] = current_mod_path .. '/Input/SpitfireLFMkIX',
            ["SpitfireLFMkIXCW_easy"] = current_mod_path .. '/Input/SpitfireLFMkIX_easy',  
        },

        Skins = {
            {
                name = _("Spitfire IX"),
                dir = "Skins/1"
            },
        },

        Missions = {
            {
                name = _("Spitfire LF Mk. IX"),
                dir = "Missions",
            },
        },

        Options = {
            {
                name = _("Spitfire LF Mk. IX"),
                nameId = "SpitfireLFMkIX",
                dir = "Options",
            },
        },

        LogBook = {
            {
                name = _("Spitfire LF Mk. IX"),
                type = "SpitfireLFMkIX",
            },
            {
                name = _("Spitfire LF Mk. IX CW"),
                type = "SpitfireLFMkIXCW",
            },
        },

        preload_resources = {
            textures = {},
            models = {},
            fonts = {},
            explosions = {},
        },

        encyclopedia_path = current_mod_path .. '/Encyclopedia',
    })

---------------------------------------------------------------------------------------------------

mount_vfs_liveries_path(current_mod_path .. "/Liveries")
mount_vfs_texture_path(current_mod_path .. "/Skins/1/ME")

dofile(current_mod_path .. "/views.lua")
make_view_settings('SpitfireLFMkIX', ViewSettings, SnapViews)
make_view_settings('SpitfireLFMkIXCW', ViewSettings, SnapViews)

make_flyable(
    'SpitfireLFMkIX',
    current_mod_path .. '/Cockpit/Scripts/',
    {self_ID, 'SpitfireLFMkIX'},
    current_mod_path .. '/comm.lua') -- make_flyable ( obj_name, optional_cockpit path, optional_fm = {mod_of_fm_origin,dll_with_fm})

make_flyable(
    'SpitfireLFMkIXCW',
    current_mod_path .. '/Cockpit/Scripts/',
    {self_ID, 'SpitfireLFMkIXCW'},
    current_mod_path .. '/comm.lua') -- make_flyable ( obj_name, optional_cockpit path, optional_fm = {mod_of_fm_origin,dll_with_fm})

---------------------------------------------------------------------------------------------------

plugin_done() -- finish declaration , clear temporal data
`

**Comment by RedK0d** [comment]
Thank you, if other issues like this, do not hesitate, you can even PR
