### ISSUE TITLE
Conflict with AH-64D

### ISSUE THREAD

**Issue by LOLBaltSS** [RedK0d/CLICKABLE-FC3#55]
New AH-64D module spawns with a Su-25T pit
[entry.lua.txt](https://github.com/RedK0d/CLICKABLE-FC3/files/8297411/entry.lua.txt)
.

**Comment by RedK0d** [comment]
Should be fixed now

**Comment by LOLBaltSS** [comment]
Confirmed resolved.  Thank you.
