### ISSUE TITLE
Add - Su27/33/J-11A RWR/SPO Buttons

### ISSUE THREAD

**Issue by deadlyfishes** [RedK0d/CLICKABLE-FC3#6]
RWR/SPO - Mode Select, Sound Signals Up/Down

**Comment by deadlyfishes** [comment]
![image](https://user-images.githubusercontent.com/25260306/151688648-82bb6ac7-aab2-4157-8e4f-bdd7172c7b69.png)

**Comment by RedK0d** [comment]
Next on the list, thanks

**Comment by deadlyfishes** [comment]
It might be these here too, or that tone knob for the RWR volume level

![image](https://user-images.githubusercontent.com/25260306/151708954-128b5a55-5cef-4916-8bf2-a18de587a548.png)
