### ISSUE TITLE
Frogfoot cockpit spawning inside hornet's

### ISSUE THREAD

**Issue by EaMS1234** [RedK0d/CLICKABLE-FC3#9]
Downloaded this mod and noted that - when it's installed, it somehow spawns the Su-25 (the one that comes with the sim) cockpit inside the F/A-18's. DCS is on open beta 2.7.10.18996 and the mod is on 0.1.0 alpha.

![Sem título](https://user-images.githubusercontent.com/52828716/151699297-437a7a2f-ceb1-4e0f-8a48-f5ebc79915c5.png)

**Comment by RedK0d** [comment]
Thanks for the report. could you try with the latest version?

**Comment by phx7** [comment]
Can confirm. Using latest version and DCS open beta.
![image](https://user-images.githubusercontent.com/3587861/151713853-b7971cd7-07a9-457c-9444-954eb69be8f4.png)

**Comment by RedK0d** [comment]
--[[Temporary fix, while waiting to create the entire list of aircraft to exclude.
Replace the lines of code in entry.lua with these. ]]
add_plugin_systems('CLICKABLE-FC3_Module','*',path,
	{
	
	
	["J-11A"] = {enable_options_key_for_unit = 'J11a_enabled'},
	["Su-27"] = {enable_options_key_for_unit = 'Su27_enabled'},
	["Su-33"] = {enable_options_key_for_unit = 'Su33_enabled'},

	["FA-18C_hornet"] = {enable_options_key_for_unit = 'dontuseit'},

	
	}	
)
plugin_done()

**Comment by EaMS1234** [comment]
@RedK0d Thank you for the answer, it fixed it for me. I will be closing the issue then.

Good luck with the project!
